wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
architecture:
  desc: null
  value: ViT-B-16
dataset:
  desc: null
  value: STL10
epochs:
  desc: null
  value: 10
label_smoothing:
  desc: null
  value: 0.0
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728244796
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.17.0
      6: 4.44.2
      8:
      - 5
      13: darwin-arm64
